### PR TITLE
What is `SetCursorVisible` ???

### PR DESCRIPTION
**Pull request by karimcambridge**

### CODE REVIEW

**Review by rt-2 — APPROVED** [review]
Thank you for catching that, that's a function in my game-mode.

**Review by rt-2 — CHANGES_REQUESTED** [review]
line 157 should not be removed?

**Comment by karimcambridge** [comment]
I'm not gonna change it, it was the final step is making the code more viewable.

**Comment by rt-2** [comment]
Why remove that comments I don't understand?

**Pull request closed without merging**
